### ISSUE TITLE
Download links need to support SSL

### ISSUE THREAD

**Issue by whyisjake** [whyisjake/Podtrac-with-Seriously-Simple-Podcasting#1]
Originally reported here: https://github.com/hlashbrooke/Seriously-Simple-Podcasting/issues/94

**Comment by whyisjake** [comment]
Following best practice, just force SSL.

**Comment by jonathanbossenger** [comment]
@whyisjake I'm working with Craig from Podcast Motor (who bought SSP from Hugh) and I've submitted a PR for this. Would be great if it could be merged so that I can let the user from the original WP.org issue can update their plugin ;) Cheers

**Comment by whyisjake** [comment]
Thanks for the PR @jonathanbossenger

**Comment by jonathanbossenger** [comment]
Anytime @whyisjake. Any change you could push this to the wp.org repo? Thanks.
